app/routes/account_routes.py
from flask import Blueprint, render_template
from flask_login import current_user


account = Blueprint("account", __name__)


@account.route("/orders", methods=["GET"])
def orders():

    return render_template(
        "account/orders.html", show_sidebar=False, active_page="orders"
    )


@account.route("/purchases", methods=["GET"])
def purchases():

    return render_template(
        "account/purchases.html", show_sidebar=False, active_page="purchases"
    )

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, flash
from flask_login import login_user, login_required, logout_user, current_user
from app.forms.auth_forms import (
    RegisterForm,
    LoginForm,
    ProfileForm,
    ChangePasswordForm,
)
from app.models.user import User

auth = Blueprint("auth", __name__)


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect("/")

    form = RegisterForm()

    if form.validate_on_submit():
        message, category = User.create(data=form.data)
        flash(message, category)
        form.data.clear()

        if category == "success":
            return redirect("/login")

    return render_template("auth/register.html", show_sidebar=False, form=form)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect("/")

    form = LoginForm()

    if form.validate_on_submit():
        user, message, category = User.find_one_by_email(form.email.data)

        if not user:
            flash(message, category)
            form.data.clear()
            return render_template("auth/login.html", show_sidebar=False, form=form)

        message, category = user.verify_password(form.password.data)

        if category == "success":
            login_user(user)
            flash(message, category)
            form.data.clear()
            return redirect("/products")
        else:
            flash(message, category)

    return render_template("auth/login.html", show_sidebar=False, form=form)


@auth.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = ProfileForm()

    if form.validate_on_submit():
        id = current_user.id
        message, category = User.update(id, form.data)

        if category == "success":
            flash(message, category)
            form.data.clear()
            return redirect("/profile")
        else:
            flash(message, category)
            form.data.clear()

    return render_template(
        "auth/profile.html",
        show_sidebar=False,
        active_page="profile",
        form=form,
    )


@auth.route("/change-password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        id = current_user.id
        message, category = User.update_password(id, form.data)

        if category == "success":
            flash(message, category)
            form.data.clear()
            return redirect("/change-password")
        else:
            flash(message, category)
            form.data.clear()

    return render_template(
        "auth/change_password.html",
        show_sidebar=False,
        active_page="change_password",
        form=form,
    )


@auth.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect("/login")

app/routes/cart_routes.py
from flask import Blueprint, render_template, redirect, request, flash
from flask_login import login_required, current_user
from app.models.cart import Cart
from app.extensions import redis
from app.config import Config

cart = Blueprint("cart", __name__)


@cart.route("/add-product-to-cart", methods=["POST"])
@login_required
def add_product_to_cart():
    product_id = request.form.get("product_id")
    quantity = int(request.form.get("quantity")) or 1

    key = f"cart:{current_user.id}"

    current_qty = redis.hget(key, product_id)
    if current_qty:
        new_qty = int(current_qty) + quantity
    else:
        new_qty = quantity

    redis.hset(key, product_id, new_qty)

    redis.expire(key, Config.CART_DURATION)

    cart, _, _ = Cart.find_cart_by_user_id(current_user.id)

    if not cart:
        cart = Cart.create_cart(user_id=current_user.id)

    message, category = Cart.add_product(
        cart_id=cart._id, product_id=product_id, quantity=quantity
    )

    if category == "success":
        flash(message, category)
        return redirect("/products")

    return redirect("/products")


@cart.route("/my-cart", methods=["GET"])
@login_required
def my_cart():
    cart, message, category = Cart.find_cart_by_user_id(current_user.id)

    if category == "error":
        flash(message, category)
        return redirect("/products")

    if cart:
        key = f"cart:{current_user.id}"
        for item in cart.products:
            product_id = item["product"]["_id"]
            current_prod = redis.hget(key, str(product_id))

            if not current_prod:
                _, _ = Cart.delete_cart_by_user_id(current_user.id)
                cart = None

    return render_template("cart/my_cart.html", show_sidebar=False, cart=cart)

app/routes/public_routes.py
from flask import Blueprint, render_template, flash, redirect, request
from datetime import datetime, timedelta, timezone
from app.models.category import Category
from app.models.product import Product

public = Blueprint("public", __name__)


@public.route("/", methods=["GET"])
def home():
    return render_template("public/home.html", show_sidebar=False, active_page="home")


@public.route("/categories", methods=["GET"])
def categories():
    sort = request.args.get("sort")
    last_week = (datetime.now(timezone.utc) - timedelta(days=7)).replace(tzinfo=None)

    categories, message, category = Category.find_all(sort)

    if category == "danger":
        flash(message, category)
        return redirect("/")

    return render_template(
        "public/categories.html",
        show_sidebar=True,
        active_page="categories",
        categories=categories,
        last_week=last_week,
        sort=sort,
    )


@public.route("/products", methods=["GET"])
def products():
    sort = request.args.get("sort")
    category_name = request.args.get("category")
    last_week = (datetime.now(timezone.utc) - timedelta(days=7)).replace(tzinfo=None)

    categories, message, category = Category.find_all("a-z")

    if category == "danger":
        flash(message, category)
        return redirect("/")

    products, message, category = Product.find_all(sort, category_name)

    if category == "danger":
        flash(message, category)
        return redirect("/")

    return render_template(
        "public/products.html",
        show_sidebar=True,
        active_page="products",
        categories=categories,
        products=products,
        last_week=last_week,
        sort=sort,
        category_name=category_name,
    )


@public.route("/products/<string:product_slug>", methods=["GET"])
def product(product_slug):
    product, message, category = Product.find_by_slug(product_slug)

    if category == "danger":
        flash(message, category)
        return redirect("/products")

    category_product, message, category = Category.find_by_id(product.category_id)

    if category == "danger":
        flash(message, category)
        return redirect("/products")

    return render_template(
        "public/product.html",
        show_sidebar=False,
        active_page="",
        product=product,
        category_product=category_product,
    )

app/templates/partials/footer.html
<footer class="footer has-background-dark has-text-light mt-6">
  <div class="content has-text-centered">
    <p>
      <strong>🛒 E-Commerce RedisMongo</strong> por
      <span class="has-text-info">Dupla 3️⃣</span>.
      <br />
      Desarrollado con ❤️ en la materia <em>Base de Datos III</em>.
    </p>
    <p>
      Código fuente con licencia
      <a
        class="has-text-warning"
        href="https://opensource.org/license/mit"
        target="_blank"
      >
        MIT </a
      >. Contenido académico bajo
      <a
        class="has-text-warning"
        href="https://creativecommons.org/licenses/by-nc-sa/4.0/"
        target="_blank"
      >
        CC BY-NC-SA 4.0 </a
      >.
    </p>
    <p>
      <a href="https://github.com/mtahuasip/e-commerce-bd-3" target="_blank">
        <i class="fab fa-github fa-lg mr-1"></i> Ver en GitHub
      </a>
    </p>
  </div>
</footer>

app/templates/partials/navbar.html
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{{ url_for('public.home') }}">
      <strong class="is-size-4 has-text-weight-bold">🛒 E-Commerce</strong>
    </a>

    <a
      role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbar-menu"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar-menu" class="navbar-menu">
    <div class="navbar-start">
      <a
        href="{{ url_for('public.home') }}"
        class="navbar-item {% if active_page == 'home' %}is-active{% endif %}"
      >
        <i class="fas fa-home mr-1"></i> Inicio
      </a>

      <a
        href="{{ url_for('public.products') }}"
        class="navbar-item {% if active_page == 'products' %}is-active{% endif %}"
      >
        <i class="fas fa-boxes mr-1"></i> Productos
      </a>

      <a
        href="{{ url_for('public.categories') }}"
        class="navbar-item {% if active_page == 'categories' %}is-active{% endif %}"
      >
        <i class="fas fa-tags mr-1"></i> Categorías
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <a class="button is-warning" href="{{ url_for('cart.my_cart') }}">
          <i class="fas fa-shopping-cart mr-1"></i> Carrito
          <span
            id="cart-count"
            class="tag is-danger is-rounded is-small cart-badge"
          >
            {{ cart_count }}
          </span>
        </a>
      </div>
      {% if not current_user.is_authenticated %}
      <div class="navbar-item">
        <a class="button is-light" href="{{ url_for('auth.login') }}">
          <i class="fas fa-sign-in-alt mr-1"></i> Iniciar sesión
        </a>
      </div>

      <div class="navbar-item">
        <a class="button is-primary" href="{{ url_for('auth.register') }}">
          <i class="fas fa-user-plus mr-1"></i> Registrarse
        </a>
      </div>
      {% endif %} {% if current_user.is_authenticated %}
      <div class="navbar-item dropdown is-hoverable">
        <div class="dropdown-trigger">
          <button
            class="button"
            aria-haspopup="true"
            aria-controls="dropdown-menu"
          >
            <span><i class="fas fa-user-circle mr-1"></i> Mi cuenta</span>
            <span class="icon is-small">
              <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
          </button>
        </div>

        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <a
              class="dropdown-item {% if active_page == 'profile' %}is-active{% endif %}"
              href="{{ url_for('auth.profile') }}"
            >
              <i class="fas fa-id-badge mr-2"></i> Mi perfil
            </a>
            <a
              class="dropdown-item {% if active_page == 'change_password' %}is-active{% endif %}"
              href="{{ url_for('auth.change_password') }}"
            >
              <i class="fa-solid fa-key mr-2"></i> Cambiar contraseña
            </a>
            <a
              class="dropdown-item {% if active_page == 'orders' %}is-active{% endif %}"
              href="{{ url_for('account.orders') }}"
            >
              <i class="fas fa-box mr-2"></i> Pedidos
            </a>
            <a
              class="dropdown-item {% if active_page == 'purchases' %}is-active{% endif %}"
              href="{{ url_for('account.purchases') }}"
            >
              <i class="fas fa-credit-card mr-2"></i> Compras
            </a>
            <hr class="navbar-divider" />
            <a
              class="dropdown-item has-text-danger"
              href="{{ url_for('auth.logout') }}"
            >
              <i class="fas fa-sign-out-alt mr-2"></i> Cerrar sesión
            </a>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

app/templates/partials/sidebar.html
<button
  id="toggleSidebar"
  class="button is-info is-fullwidth is-hidden-tablet mb-3"
>
  <i class="fas fa-sliders-h mr-2"></i> Filtros
</button>

<aside id="sidebar" class="menu is-hidden-mobile">
  {% if active_page == 'products' %}
  <p class="menu-label">Filtrar por</p>
  <ul class="menu-list">
    <li>
      <a href="{{ url_for('public.products') }}">
        <i class="fas fa-sort mr-2"></i> Ordenar por
      </a>
      <ul>
        <li>
          <a
            href="{{ url_for('public.products', sort='a-z', category=category_name) }}"
            class="{% if sort == 'a-z' %}is-active{% endif %}"
          >
            <i class="fas fa-sort-alpha-down mr-2"></i> A-Z
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('public.products', sort='z-a', category=category_name) }}"
            class="{% if sort == 'z-a' %}is-active{% endif %}"
          >
            <i class="fas fa-sort-alpha-up mr-2"></i> Z-A
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('public.products', sort='price-asc', category=category_name) }}"
            class="{% if sort == 'price-asc' %}is-active{% endif %}"
          >
            <i class="fas fa-sort-amount-down mr-2"></i> Precio: menor a mayor
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('public.products', sort='price-desc', category=category_name) }}"
            class="{% if sort == 'price-desc' %}is-active{% endif %}"
          >
            <i class="fas fa-sort-amount-up mr-2"></i> Precio: mayor a menor
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('public.products', sort='newest', category=category_name) }}"
            class="{% if sort == 'newest' %}is-active{% endif %}"
          >
            <i class="fas fa-clock mr-2"></i> Más recientes
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('public.products', sort='oldest', category=category_name) }}"
            class="{% if sort == 'oldest' %}is-active{% endif %}"
          >
            <i class="fas fa-clock mr-2"></i> Más antiguos
          </a>
        </li>
      </ul>
    </li>

    <li>
      <a href="{{ url_for('public.products') }}">
        <i class="fas fa-tags mr-2"></i> Categorías
      </a>
      <ul>
        {% for category in categories %}
        <li>
          <a
            href="{{ url_for('public.products', category=category.slug, sort=sort) }}"
            class="{% if category_name == category.slug %}is-active{% endif %}"
          >
            {{ category.name }}</a
          >
        </li>
        {% endfor %}
      </ul>
    </li>
  </ul>
  {% elif active_page == 'categories' %}
  <p class="menu-label">Ordenar categorías</p>
  <ul class="menu-list">
    <li>
      <a
        href="/categories?sort=a-z"
        class="{% if sort == 'a-z' %}is-active{% endif %}"
        ><i class="fas fa-sort-alpha-down mr-2"></i> A-Z</a
      >
    </li>
    <li>
      <a
        href="/categories?sort=z-a"
        class="{% if sort == 'z-a' %}is-active{% endif %}"
        ><i class="fas fa-sort-alpha-up mr-2"></i> Z-A</a
      >
    </li>
    <li>
      <a
        href="/categories?sort=newest"
        class="{% if sort == 'newest' %}is-active{% endif %}"
        ><i class="fas fa-clock mr-2"></i> Más recientes</a
      >
    </li>
    <li>
      <a
        href="/categories?sort=oldest"
        class="{% if sort == 'oldest' %}is-active{% endif %}"
        ><i class="fas fa-clock mr-2"></i> Más antiguos</a
      >
    </li>
    <li>
      <a
        href="/categories?sort=stock"
        class="{% if sort == 'stock' %}is-active{% endif %}"
        ><i class="fas fa-check-circle mr-2"></i>Con stock</a
      >
    </li>
    <li>
      <a
        href="/categories?sort=no-stock"
        class="{% if sort == 'no-stock' %}is-active{% endif %}"
        ><i class="fas fa-times-circle mr-2"></i> Sin stock</a
      >
    </li>
  </ul>
  {% else %}
  <p class="menu-label">Menú</p>
  <ul class="menu-list">
    <li>
      <a><i class="fas fa-tachometer-alt mr-2"></i> Dashboard</a>
    </li>
    <li>
      <a><i class="fas fa-users mr-2"></i> Clientes</a>
    </li>
  </ul>
  {% endif %}
</aside>